config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :books, except: %i[edit update destroy] do
      get 'image'
    end
  end
  resources :books, except: %i[edit update destroy] do
    get 'image'
    resources :ratings, only: %i[create update]
    resources :comments, only: :create
    resources :histories, only: :create
  end
  devise_for :users
  authenticated :user do
    root 'books#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String
  field :user_id, type: String
  field :book_id, type: String

  belongs_to :book, counter_cache: :comments_count
  belongs_to :user

  validates :user_id, :book_id, :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new comment_params
    @comment.book_id = params[:book_id]
    respond_to do |format|
      if @comment.save
        format.js {}
      else
        format.js { render status: :bad_request }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
.comment-new
  .text-center.rounded.shadow
    = form_for @book.comments.new, url: book_comments_path(@book), remote: true do |f|
      .field.mx-3
        = f.text_area :body, id: 'commentBodyField', placeholder: 'Comment here', hide_label: true, class: 'form-control align-center hide-shadow'
      %br
      .actions
        = f.submit 'Send', class: 'btn btn-outline-success full-width hide-shadow'

app/views/comments/_history.html.haml
- @comments.each do |comment|
  = render 'comments/show', comment: comment
- unless @comments.empty?
  = render 'comments/pagina'

app/views/comments/_pagina.html.haml
.row
  .col
  .col-6
    %ul.pagination.justify-content-center
      - unless @comments.first_page?
        %li.page-item
          = link_to 'Previous', book_path(@book, page: @comments.current_page - 1), remote: true, class: 'page-link'
      - unless @comments.last_page?
        %li.page-item
          = link_to 'Next', book_path(@book, page: @comments.current_page + 1), remote: true, class: 'page-link'
  .col

app/views/comments/_show.html.haml
.comment.m-3
  .text-left
    .author
      .text-muted
        %b
          = comment.user.email
  %br
  .text-center
    .body
      %h6
        = comment.body
  .text-right
    .date
      %p
      = comment.created_at.strftime('%d/%m/%Y %H:%M')
  %hr
  %br

app/views/comments/create.js.erb
<%- unless @comment.errors.any? %>
$('#commentBodyField').val('');
$('.all-comments')
    .animate({opacity: 0.95})
    .prepend('<%= escape_javascript(render 'show', comment: @comment) %>');
<%- end %>