config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :books, except: %i[edit update destroy] do
      get 'image'
    end
  end
  resources :books, except: %i[edit update destroy] do
    get 'image'
    resources :ratings, only: %i[create update]
    resources :comments, only: :create
    resources :histories, only: :create
  end
  devise_for :users
  authenticated :user do
    root 'books#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/models/history.rb
# frozen_string_literal: true

class History
  include Mongoid::Document

  after_save :change_book_state

  field :taken, type: Boolean
  field :user_id, type: String
  field :book_id, type: String

  belongs_to :book, counter_cache: :histories_count
  belongs_to :user

  validates :user_id, :book_id, :taken, presence: true

  def change_book_state
    book.update(taken: taken, taker_id: taken ? user_id : nil)
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    if @book.taken && history_params[:taken] == 'true' # wtf?
      respond_to do |format|
        format.js { render status: :bad_request }
      end
    else
      @history = current_user.histories.new history_params
      @history.book_id = @book.id
      @book = @history.book
      respond_to do |format|
        if @history.save
          format.js {}
        else
          format.js { render status: :bad_request }
        end
      end
    end
  end

  private

  def history_params
    params.require(:history).permit(:taken)
  end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.haml
- if @book.taken && @book.taker_id.to_s != current_user.id.to_s
  %span.fa.fa-times-circle.fa-4x.red{ 'data-toggle': 'tooltip', 'title': 'Book already is taken' }
- else
  = form_for @book.histories.new, url: book_histories_path(@book), remote: true do |f|
    - if @book.taken && @book.taker_id.to_s == current_user.id.to_s
      = f.hidden_field :taken, value: false
      = button_tag type: 'submit', class: 'btn-hidden' do
        %span.fa.fa-undo.fa-4x.orange{ 'data-toggle': 'tooltip', 'title': 'Return the book' }
    - else
      = f.hidden_field :taken, value: true
      = button_tag type: 'submit', class: 'btn-hidden' do
        %span.fa.fa-check-circle.fa-4x.green{ 'data-toggle': 'tooltip', 'title': 'Book is available', 'aria-hidden': true }

app/views/histories/create.js.erb
$('.status')
    .empty()
    .append('<%= escape_javascript(render 'histories/form', history: History.new) %>');