config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :books, except: %i[edit update destroy] do
      get 'image'
    end
  end
  resources :books, except: %i[edit update destroy] do
    get 'image'
    resources :ratings, only: %i[create update]
    resources :comments, only: :create
    resources :histories, only: :create
  end
  devise_for :users
  authenticated :user do
    root 'books#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/models/rating.rb
# frozen_string_literal: true

class Rating
  include Mongoid::Document

  after_create :incr_votes

  field :user_id, type: String
  field :book_id, type: String
  field :rating, type: Integer, default: 0

  belongs_to :book, counter_cache: :votes_count
  belongs_to :user

  validates :user_id, :book_id, presence: true
  validates :rating, inclusion: { in: 1..5 }

  def incr_votes
    book.inc(votes: 1)
  end
end

app/controllers/ratings_controller.rb
# frozen_string_literal: true

class RatingsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    if @book.current_rate(current_user.id).nil?
      @rating = current_user.ratings.new rating_params
      @rating.book_id = @book.id
      respond_to do |format|
        if @rating.save
          format.js {}
        else
          format.js { render status: :bad_request }
        end
      end
    else
      respond_to do |format|
        format.js { render status: :bad_request }
      end
    end
  end

  def update
    @rating = Rating.find(params[:id])
    @book = @rating.book
    respond_to do |format|
      if @rating.update rating_params
        format.js {}
      else
        format.js { render status: :bad_request }
      end
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:rating)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.haml
- if @rating.present?
  = form_for @rating, url: book_rating_path(@book, @rating), remote: true do |f|
    = f.hidden_field :rating, id: 'ratingFormRate'
    = f.submit style: 'display: none;', id: 'ratingFormSubmit'
- else
  = form_for Rating.new, url: book_ratings_path(@book), remote: true do |f|
    = f.hidden_field :rating, id: 'ratingFormRate'
    = f.submit style: 'display: none;', id: 'ratingFormSubmit'
- 5.times do |i|
  - if @book.rating >= i + 1
    %span.fa.fa-star.fa-3x.gold{ onclick: "setRating(#{i + 1})" }
  - else
    %span.fa.fa-star.fa-3x.grey{ onclick: "setRating(#{i + 1})" }

app/views/ratings/_info.html.haml
%h5= "Your rating: #{ @book.current_rate(current_user.id.to_s)&.rating || '-' }"
%h6= "All votes: #{ @book.votes }"

app/views/ratings/create.js.erb
<%- unless @rating.nil? %>
  $('.rating')
      .empty()
      .append('<%= escape_javascript(render 'ratings/form') %>');
  triggerHover();
  $('.rating-status')
      .empty()
      .append('<%= escape_javascript(render 'ratings/info') %>');
<%- end %>

app/views/ratings/update.js.erb
<%- unless @rating.nil? %>
  $('.rating')
      .empty()
      .append('<%= escape_javascript(render 'ratings/form') %>');
  triggerHover();
  $('.rating-status')
      .empty()
      .append('<%= escape_javascript(render 'ratings/info') %>');
<%- end %>