config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :books, except: %i[edit update destroy] do
      get 'image'
    end
  end
  resources :books, except: %i[edit update destroy] do
    get 'image'
    resources :ratings, only: %i[create update]
    resources :comments, only: :create
    resources :histories, only: :create
  end
  devise_for :users
  authenticated :user do
    root 'books#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/models/book.rb
# frozen_string_literal: true

class Book
  include Mongoid::Document
  include Mongoid::Timestamps
  mount_uploader :image, ImageUploader

  field :title, type: String
  field :author, type: String
  field :description, type: String
  field :user_id, type: String
  field :votes, type: Integer, default: 0
  field :taken, type: Boolean, default: false
  field :taker_id, type: String, default: nil
  field :image, type: BSON::ObjectId

  belongs_to :user
  has_many :histories, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, :author, :description, :taken, presence: true

  def rating
    return 0 unless ratings.present?
    (ratings.map(&:rating).inject(0, &:+) / ratings.size).round
  end

  def current_rate(user_id)
    Rating.where(user_id: user_id, book_id: id)&.first
  end
end

app/controllers/api/v1/books_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BooksController < ApplicationController

      def index
        @books = Book.page(params[:page]).per(20)
        @top_books = Book.order(votes_count: :desc, histories_count: :desc).limit(5)
      end

      def show
        @book = Book.find(params[:id])
        @comments = @book.comments.order_by(created_at: :desc).page(params[:page]).per(10)
        @rating = @book.current_rate(current_user.id.to_s)
      end

      def image
        @book = Book.find(params[:book_id])
        self.response_body = if params[:version]
                               @book.image.send(params[:version].to_sym).read
                             else
                               @book.image.read
                             end
        self.content_type = @book.image.content_type
      rescue
        head :not_found
      end

      private

      def book_params
        params.require(:book).permit %i[title author description image]
      end
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController

  def index
    @books = Book.page(params[:page]).per(20)
    @top_books = Book.order(votes_count: :desc, histories_count: :desc).limit(5)
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments.order_by(created_at: :desc).page(params[:page]).per(10)
    @rating = @book.current_rate(current_user.id.to_s)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new book_params
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, success: 'Book was successfully created.' }
      else
        format.html { render :new, status: :bad_request }
      end
    end
  end

  def image
    @book = Book.find(params[:book_id])
    self.response_body = if params[:version]
                           @book.image.send(params[:version].to_sym).read
                         else
                           @book.image.read
                         end
    self.content_type = @book.image.content_type
  rescue
    head :not_found
  end

  private

  def book_params
    params.require(:book).permit %i[title author description image]
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_all_books.html.haml
.paginated-books
  %table.table.table-bordered.table-hover.table-custom.all-books-table
    %thead
      %tr.text-center
        %th Name
        %th Author
        %th Status
    %tbody
      - @books.each do |book|
        %tr.text-center
          %td
            %h4
              = link_to book.title, book
          %td
            = book.author
          %td
            - if book.taken
              %span.fa.fa-times-circle.fa-2x.red{ 'data-toggle': 'tooltip', 'title': 'Book already is taken' }
            -else
              %span.fa.fa-check-circle.fa-2x.green{ 'data-toggle': 'tooltip', 'title': 'Book is available' }
  .row
    .col
    .col-6
      %ul.pagination.justify-content-center
        - unless @books.first_page?
          %li.page-item
            = link_to 'Previous', books_path(page: @books.current_page - 1), remote: true, class: 'page-link'
        - unless @books.last_page?
          %li.page-item
            = link_to 'Next', books_path(page: @books.current_page + 1), remote: true, class: 'page-link'
    .col

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    .notification
      %h2= 'You have some errors:'
      %ul
        - @book.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.text_field :title, placeholder: :title, class: 'form-control'
  .form-group
    = f.text_field :author, placeholder: :author, class: 'form-control'
  .form-group
    = f.text_field :description, placeholder: :description, class: 'form-control'
  .form-group
    .row
      .col
        = f.label 'Cover image: ', class: 'float-left text-muted'
      .col
        = f.file_field :image
  %hr
  .actions
    = f.submit 'Save', class: 'btn btn-outline-success full-width hide-shadow'

app/views/books/index.html.haml
.books
  .bg-container#mb_parallax_one
    .mb_parallax_overlay
      .text-center
        %h1
          Top books
        %h5
          Based on the number of readers for all time
    .top-books
      %table.table.table-bordered.table-hover.table-custom.top-books-table
        %thead
          %tr.text-center
            %th
            %th Name
            %th Author
            %th Status
        %tbody
          - @top_books.each_with_index do |book, index|
            %tr.text-center
              %td
                %p= index += 1
              %td
                %h4
                  = link_to book.title, book
              %td
                %p= book.author
              %td
                - if book.taken
                  %span.fa.fa-times-circle.fa-2x.red{ 'data-toggle': 'tooltip', 'title': 'Book already is taken' }
                -else
                  %span.fa.fa-check-circle.fa-2x.green{ 'data-toggle': 'tooltip', 'title': 'Book is available' }
      %br
    %br
  .bg-container#mb_parallax_two
    .mb_parallax_overlay
      .text-center
        %h2
          All books
        %h5
          All available books at the our library
    .all-books
      = render 'all_books'
    %br

app/views/books/index.js.erb
$('.all-books')
    .empty()
    .append('<%= escape_javascript(render partial: 'all_books') %>');

app/views/books/new.html.haml
.book-new
  .container
    %br
    .text-center
      .title
        %h2 Create a new book
        %hr.half-width
      .form
        = render 'books/form'
        %hr.half-width

app/views/books/show.html.haml
.book-show.pt-3
  .container-fluid
    .row
      .col-sm-12.col-md-12.col-lg-4.col-xl-4
        .cover.rounded
          = image_tag(book_image_path(@book.id, version: :large))
        .rating.d-flex.justify-content-center
          = render 'ratings/form', rating: @rating
        .rating-status.text-center
          = render 'ratings/info'
        %hr.half-width
      .col-sm-12.col-md-12.col-lg-8.col-xl-8
        .info
          .text-right
            .status
              = render 'histories/form', history: History.new
          .text-center
            .title
              %h2= @book.title
            .author
              .text-right
                .text-grey
                  %h4= @book.author
          .description
            %p= @book.description
        %hr
        .comments
          .text-center
            %h4 Comments
            %hr.half-width
          = render 'comments/form'
          %hr
          .all-comments
            = render 'comments/history'

app/views/books/show.js.erb
$('.all-comments')
    .empty()
    .append('<%= escape_javascript(render partial: 'comments/history') %>');